# Generated by Django 5.0.3 on 2024-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='data science', max_length=100),
            preserve_default=False,
        ),
    ]
