# Generated by Django 5.0.3 on 2024-04-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_coursename_course_instructor_course_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
